@echo off
echo Starting LinkPro Analytics API...
cd /d "%~dp0"
echo Activating virtual environment...
call venv\Scripts\activate
echo Starting server with hot reload...
uvicorn src.app:app --reload --host 0.0.0.0 --port 8000
pause